In [1]:
from iads.data_traitement import traitement
from iads.nlp import preprocessing

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

# I. Chargement des données :

In [2]:
df_jeux = pd.read_csv("../data/details_desc.csv")
df_jeux.head(2)

Nombre d'avis            full_title  Note rectifiée  Note  Note Finkel  \
0           19.0  Marvel United (2020)            8.40  7.58         8.74   
1           33.0      Mariposas (2020)            7.29  7.39         7.68   

  categories  Nombre d'avis rectifiés  \
0        NaN                     10.0   
1        NaN                     17.0   

                                         description          titre  \
0  marvel united unir contre super vilain red sku...  Marvel United   
1  annee printemps million papillon monarque quit...      Mariposas   

             _id  ...       editors distributors nb_players age_required  \
0  marvel-united  ...  CMON Limited          NaN        1-4        14-99   
1      mariposas  ...       Gigamic          NaN        2-5        14-99   

  duration enfant  ado  adulte  solo  multi  
0     45.0      0    1       1     1      1  
1     60.0      0    1       1     0      1  

[2 rows x 22 columns]

In [3]:
df_avis = pd.read_csv("../data/avis_clean.csv")
df_avis.head(2)

comment  date_published  \
0  Lorsque le jeu est jeu, bon, réflexif, joli po...            2021   
1  Comment continuer après un mega hit ? Simpleme...            2020   

                          title_review      title  note              author  \
0  Voyages sur les ailes des papillons  Mariposas   8.0  Monsieur Guillaume   
1             le festival de Michoacan  Mariposas   7.0          morlockbob   

   treated title_id_jeu  
0     True    mariposas  
1     True    mariposas

In [4]:
len(np.unique(df_avis["title_id_jeu"]))

10936

In [5]:
len(np.unique(df_jeux["_id"]))

16873

In [6]:
# users = list(df_avis['author'].unique())
# games = list(df_jeux['_id'].unique())

# ratings_matrix = np.zeros((len(users), len(games)))

# for _, row in tqdm(df_avis.iterrows(), total=len(df_avis)):
#     i = users.index(row['author'])
#     j = games.index(row['title_id_jeu'])
    
#     ratings_matrix[i, j] = row['note']

In [21]:
users = df_avis['author'].unique()
games = df_jeux['_id'].unique()

ratings_matrix = np.zeros((len(users), len(games)))

for i, user in tqdm(enumerate(users), total=len(users), desc='Processing users'):
    user_games = df_avis[df_avis['author'] == user].groupby('title_id_jeu')
    
    for game, reviews in user_games:
        j = np.where(games == game)[0][0]
        max_date = reviews['date_published'].max()
        ratings_matrix[i, j] = reviews[reviews['date_published'] == max_date].iloc[0]["note"]

Processing users: 100%|██████████| 13623/13623 [03:59<00:00, 56.91it/s] 


In [22]:
print(ratings_matrix)

[[0. 8. 0. ... 0. 0. 0.]
 [0. 7. 7. ... 0. 0. 0.]
 [0. 7. 8. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
